/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package shopping_management_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class Customer_Bill_Generation_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Customer_Bill_Generation_Admin
     */
    public Customer_Bill_Generation_Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        one_tie_socks = new javax.swing.JCheckBox();
        two_shirts = new javax.swing.JCheckBox();
        combo_one_jeans_one_shirt = new javax.swing.JCheckBox();
        one_blazer = new javax.swing.JCheckBox();
        food_items2 = new javax.swing.JLabel();
        combo_blazer = new javax.swing.JCheckBox();
        two_tshirts = new javax.swing.JCheckBox();
        two_jeans = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        female = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        mobile_no = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        one_jeans = new javax.swing.JCheckBox();
        gender1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adress = new javax.swing.JTextArea();
        total_bill1 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        combo_one_jeans_one_tshirt = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        combo_without_blazer = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        food_items1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        food_items = new javax.swing.JLabel();
        one_tshirt = new javax.swing.JCheckBox();
        one_shirt = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        one_tie_socks.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        one_tie_socks.setText("ONE TIE AND ONE SOCKS");

        two_shirts.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        two_shirts.setText("TWO SHIRTS");

        combo_one_jeans_one_shirt.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        combo_one_jeans_one_shirt.setText("COMBO(ONE JEANS AND ONE SHIRT)");

        one_blazer.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        one_blazer.setText("ONE BLAZER");

        food_items2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        food_items2.setText("PRICE");

        combo_blazer.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        combo_blazer.setText("COMBO(ONE EACH WITH BLAZER)");

        two_tshirts.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        two_tshirts.setText("TWO T-SHIRTS");

        two_jeans.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        two_jeans.setText("TWO JEANS");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setText(" CUSTOMER SHOPPING AND BILL GENERATION");

        male.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        male.setSelected(true);
        male.setText("  MALE");
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel6.setText("RS 300");

        female.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        female.setText(" FEMALE");
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel7.setText("RS 600");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("  NAME");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("RS 500");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("RS 100");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("  MOBILE NO.");
        jLabel3.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("RS 3500");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("RS 1200");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("  ADRESS");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("RS 2000");

        one_jeans.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        one_jeans.setText("ONE JEANS");

        gender1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gender1.setText("  GENDER");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("RS 1000");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("RS 1500");

        adress.setColumns(20);
        adress.setRows(5);
        jScrollPane1.setViewportView(adress);

        total_bill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_bill1ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("PLACE ORDER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText("BACK");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("ORDER MORE FOOD ITEMS");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        combo_one_jeans_one_tshirt.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        combo_one_jeans_one_tshirt.setText("COMBO(ONE JEANS AND ONE T-SHIRT)");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("TOTAL_BILL");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("RS 900");

        combo_without_blazer.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        combo_without_blazer.setText("COMBO(ONE EACH WITHOUT BLAZER)");
        combo_without_blazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_without_blazerActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setText("RS 1100");

        food_items1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        food_items1.setText("SELECT ANY ONE SHOPPING ITEM");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setText("RS 600");

        food_items.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        food_items.setText("CLOTH ITEMS");

        one_tshirt.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        one_tshirt.setText("ONE T-SHIRT");

        one_shirt.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        one_shirt.setText("ONE SHIRT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gender1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(144, 144, 144)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(male)
                        .addGap(106, 106, 106)
                        .addComponent(female))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(name)
                        .addComponent(mobile_no)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(food_items1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(two_shirts, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(two_tshirts, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(two_jeans, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(one_tshirt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(one_shirt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(one_blazer, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(combo_blazer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(combo_one_jeans_one_tshirt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(combo_without_blazer, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(combo_one_jeans_one_shirt)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(total_bill1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(food_items, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(120, 120, 120)))
                            .addComponent(one_tie_socks)
                            .addComponent(one_jeans, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(food_items2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(106, 106, 106)
                                .addComponent(jButton6)
                                .addGap(31, 31, 31)
                                .addComponent(jButton5))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(mobile_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(male)
                        .addComponent(gender1))
                    .addComponent(female, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(food_items2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(jLabel17)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel14))))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(food_items, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(one_tshirt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(one_shirt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(one_jeans)
                                .addGap(6, 6, 6)
                                .addComponent(one_tie_socks)
                                .addGap(7, 7, 7)
                                .addComponent(two_tshirts)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(two_shirts)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(two_jeans)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(one_blazer, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(combo_blazer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_without_blazer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_one_jeans_one_tshirt)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_one_jeans_one_shirt))))
                    .addComponent(food_items1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_bill1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void total_bill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_bill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_total_bill1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String s=name.getText();
        String s2=mobile_no.getText();
        String s3=adress.getText();

        String gender="";
        int tshirt_bill=0;
        int shirt_bill=0;
        int jeans_bill=0;
        int tie_socks_bill=0;
        int blazer_bill=0;
        int total=0;
        if(male.isSelected())
        {
            gender="Male";
        }

        if(female.isSelected())
        {
            gender="Female";
        }

        String items="";

        if(one_tshirt.isSelected());
        {
            items="one t-shirt ";
        }

        if(one_shirt.isSelected())
        {
            items="one shirt ";
        }

        if(one_jeans.isSelected())
        {
            items="one jeans ";
        }
        if(one_tie_socks.isSelected())
        {
            items="one tie and socks pair ";
        }
        if(two_shirts.isSelected())
        {
            items="two shirts ";
        }
        if(one_blazer.isSelected())
        {
            items="one blazer ";
        }
        if(combo_blazer.isSelected())
        {
            items="combo(all with blazer) ";
        }
        if(combo_without_blazer.isSelected())
        {
            items="combo(all without blazer) ";
        }
        if(combo_one_jeans_one_tshirt.isSelected())
        {
            items="one jeans,t-shirt ";
        }
        if(combo_one_jeans_one_shirt.isSelected())
        {
            items="one jeans,shirt ";
        }
        if(two_tshirts.isSelected())
        {
            items="two shirts ";
        }
        if(two_jeans.isSelected())
        {
            items="two jeans ";
        }
        if(one_tshirt.isSelected())
        {
            tshirt_bill=300;
            total=tshirt_bill;
            total_bill1.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(Customer_Bill_Generation_Admin.this,"Bill Generated Successfully...total bill is rs:"+total);
        }
        if(one_shirt.isSelected())
        {
            shirt_bill=500;
            total=shirt_bill;
            total_bill1.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(Customer_Bill_Generation_Admin.this,"Bill Generated Successfully...total bill is rs:"+total);
        }

        if(one_jeans.isSelected())
        {
            jeans_bill=600;
            total=jeans_bill;
            total_bill1.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(Customer_Bill_Generation_Admin.this,"Bill Generated Successfully...total bill is rs:"+total);
        }
        if(one_tie_socks.isSelected())
        {
            tie_socks_bill=100;
            total=tie_socks_bill;
            total_bill1.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(Customer_Bill_Generation_Admin.this,"Bill Generated Successfully...total bill is rs:"+total);
        }
        if(two_tshirts.isSelected())
        {
            tshirt_bill=300;
            total=2*tshirt_bill;
            total_bill1.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(Customer_Bill_Generation_Admin.this,"Bill Generated Successfully...total bill is rs:"+total);
        }
        if(two_shirts.isSelected())
        {
            shirt_bill=500;
            total=2*shirt_bill;
            total_bill1.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(Customer_Bill_Generation_Admin.this,"Bill Generated Successfully...total bill is rs:"+total);
        }
        if(two_jeans.isSelected())
        {
            jeans_bill=600;
            total=2*jeans_bill;
            total_bill1.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(Customer_Bill_Generation_Admin.this,"Bill Generated Successfully...total bill is rs:"+total);
        }
        if(one_blazer.isSelected())
        {
            blazer_bill=2000;
            total=blazer_bill;
            total_bill1.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(Customer_Bill_Generation_Admin.this,"Bill Generated Successfully...total bill is rs:"+total);
        }
        if(combo_blazer.isSelected())
        {
            tshirt_bill=300;
            shirt_bill=500;
            jeans_bill=600;
            tie_socks_bill=100;
            blazer_bill=2000;
            total=(tshirt_bill+shirt_bill+jeans_bill+tie_socks_bill+blazer_bill)-100;
            total_bill1.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(Customer_Bill_Generation_Admin.this,"Bill Generated Successfully...you are eligible for rs 100 discount total bill is rs:"+total);
        }

        if(combo_without_blazer.isSelected())
        {
            tshirt_bill=300;
            shirt_bill=500;
            jeans_bill=600;
            tie_socks_bill=100;
            total=tshirt_bill+shirt_bill+jeans_bill+tie_socks_bill;
            total_bill1.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(Customer_Bill_Generation_Admin.this,"Bill Generated Successfully...total bill is rs:"+total);
        }
        if(combo_one_jeans_one_tshirt.isSelected())
        {
            jeans_bill=600;
            tshirt_bill=300;
            total=jeans_bill+tshirt_bill;
            total_bill1.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(Customer_Bill_Generation_Admin.this,"Bill Generated Successfully...total bill is rs:"+total);
        }
        if(combo_one_jeans_one_shirt.isSelected())
        {
            jeans_bill=600;
            shirt_bill=500;
            total=jeans_bill+shirt_bill;
            total_bill1.setText(String.valueOf(total));
            JOptionPane.showMessageDialog(Customer_Bill_Generation_Admin.this,"Bill Generated Successfully...total bill is rs:"+total);
            total_bill1.setText(String.valueOf(total));
        }

        try{

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql:///shopping_management_system","root","");
            PreparedStatement p=con.prepareStatement("insert into bill_generation_table (`name`,`mobile_no`,`adress`,`gender`,`cloth_items`,`total_bill`)values('"+s+"','"+s2+"','"+s3+"','"+gender+"','"+items+"','"+total+"')");

            int i=p.executeUpdate();
            System.out.println("Shopping Order Placed Successfully");
            p.close();
            con.close();
        }
        catch(Exception e1)
        {
            System.out.println(e1);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Admin_Activity s=new Admin_Activity();
        s.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Customer_Bill_Generation_Admin s=new Customer_Bill_Generation_Admin();
        s.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void combo_without_blazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_without_blazerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_without_blazerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_Bill_Generation_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_Bill_Generation_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_Bill_Generation_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_Bill_Generation_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_Bill_Generation_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea adress;
    private javax.swing.JCheckBox combo_blazer;
    private javax.swing.JCheckBox combo_one_jeans_one_shirt;
    private javax.swing.JCheckBox combo_one_jeans_one_tshirt;
    private javax.swing.JCheckBox combo_without_blazer;
    private javax.swing.JRadioButton female;
    private javax.swing.JLabel food_items;
    private javax.swing.JLabel food_items1;
    private javax.swing.JLabel food_items2;
    private javax.swing.JLabel gender1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField mobile_no;
    private javax.swing.JTextField name;
    private javax.swing.JCheckBox one_blazer;
    private javax.swing.JCheckBox one_jeans;
    private javax.swing.JCheckBox one_shirt;
    private javax.swing.JCheckBox one_tie_socks;
    private javax.swing.JCheckBox one_tshirt;
    private javax.swing.JTextField total_bill1;
    private javax.swing.JCheckBox two_jeans;
    private javax.swing.JCheckBox two_shirts;
    private javax.swing.JCheckBox two_tshirts;
    // End of variables declaration//GEN-END:variables
}
